### PR TITLE
fix(als.py): No need to convert user_items or react_users to csr if t…

### PR DESCRIPTION
**Pull request by tripathiaakash**
…hey are already in csr format

Added conditional return statements to recalculate_user and recalculate_item functions. This bypasses the time expenditure during csr conversion. Helpful when one has to calculate user and item latent vectors for hundreds of thousands of items,

### CODE REVIEW

**Comment by benfred** [comment]
I'm not sure I totally understand this PR -  if the input matrix is already a CSR, the conversion is a no-op:  https://github.com/scipy/scipy/blob/102b7fa5a2f2f97715ef5c40902e1c6f73c19941/scipy/sparse/csr.py#L167-L171

Calling '.tocsr' on a csr matrix is slightly faster for me than calling `getformat` on the matrix to avoid the tocsr conversion:

```python
In [12]: %timeit plays.getformat()
164 ns ± 0.397 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [13]: %timeit plays.tocsr()
126 ns ± 0.744 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

Whats you use case here?  The 'recalculate_user' code is super slow right now since its hitting an unoptimized pure python code path - rather than the optimized versions we have in cython/c++. If you're hitting this 100k+ times there is probably a better solution

**Comment by tripathiaakash** [comment]
For me, the time taken for both the functions is different by orders of magnitude (milliseconds vs nanoseconds).

image

The sparse matrix in the above image is:
<41821x12407 sparse matrix of type '<class 'numpy.float64'>'
	with 440416 stored elements in List of Lists format>

For getformat() --> time taken = 160 ns ± 0.0258 ns
For tocsr() --> time taken = 52.5 ms ± 102 µs

So, in a case of a big enough matrix, getformat() is much faster than tocsr()

**Comment by benfred** [comment]
>  <41821x12407 sparse matrix of type '<class 'numpy.float64'>'
with 440416 stored elements in List of Lists format>

I don't think you're benchmarking the same thing as me - it looks like your matrix is in 'List of Lists' format rather than a CSR format. Converting from a lists-of-lists formatted matrix to CSR will take time - but converting from CSR to CSR won't. (also the 'getformat() function from your matrix will return 'lil' so you'll still incur the tocsr overhead with this PR).

Can you try again with a CSR matrix?

**Comment by tripathiaakash** [comment]
Ok. I got it now. If we input the CSR matrix as user_item, it will be fast but if we input any other format, it will be converted into CSR first (which is expensive) and then the computation will take place. So, it will work both ways. It's better to input CSR format for recalculating latent vectors for 100K users.

Thanks for the input :)

**Comment by tripathiaakash** [comment]
Closing the pull request now.

**Pull request closed without merging**
