### PR TITLE
[WIP] random_state parameter to permit controlled item_factors, user_factors seeding

### PR DESCRIPTION
**Pull request by tgsmith61591**
I added an optional `random_state` parameter to the following classes:

* `AlternatingLeastSquares`
* `NMSLibAlternatingLeastSquares`
* `AnnoyAlternatingLeastSquares`
* `FaissAlternatingLeastSquares`
* `BayesianPersonalizedRanking`
* `LogisticMatrixFactorization`

This parameter behaves very similarly to sklearn's `random_state` parameters, and allows a user to control the initialization of the item and product factor matrices for reproducibility at the constructor level, rather that setting `np.random.seed` in various places.

### CODE REVIEW

**Comment by benfred** [comment]
So - I think that the unittest's here are throwing some false positives with these changes.

What used to happen is that I set the seed explicitly for the unittests to reduce random errors:
https://github.com/benfred/implicit/blob/master/tests/als_test.py#L111 by calling ```np.random.seed```.

This meant that each unittest run was optimizing the same randomly chosen initial factors. With this change, I don't think calling np.random_seed has any effect - introducing some non-deterministic behaviour in the unittest. I restarted the unittest jobs that failed and it looks like they worked the second time through anyways.

Can you change the unittest to set an explicit seed when training this? It also might be worth reducing the required precision for that test: the error was something like ```AssertionError: 1.0 != 1.0001273 within 0.0001 delta``` - meaning even with the random seed it almost worked

**Comment by tgsmith61591** [comment]
Yes, absolutely can and will push again shortly!

**Comment by roseaysina** [comment]
@tgsmith61591 @benfred Hello there! 

Is there any progress on this PR? It is almost two years since the first activity here.
The inability to reproduce results is very critical in experiments, and setting `np.random.seed(seed)` doesn't help.

Please, it will be great if this feature will be finally implemented.

**Comment by tgsmith61591** [comment]
Sorry, shortly after opening this I changed jobs and left my fork on my old computer. I'll try to look for some time to pick up where I left off.

**Comment by tgsmith61591** [comment]
Sorry for the CI spam, @benfred. Looks like the Apple 2.7 build is unhappy... will take a look into it later on when I get a chance. But for now, everything else is passing.

**Comment by ita9naiwa** [comment]
Great! Thanks!

**Comment by ita9naiwa** [comment]
is it okay to merge this? it has WIP at title...

**Comment by tgsmith61591** [comment]
Sorry, never edited the title. Finally got Travis to pass, so I think it was good to merge 😄

**Comment by syahrulhamdani** [comment]
Hi @tgsmith61591, does this feature has been released yet? I've installed `0.4.2` but can't find the `random_state` parameter. Also, I notice this in the [`setup.py`](https://github.com/benfred/implicit/blob/master/setup.py#L14).
```
VERSION = "0.4.0"
```

**Pull request merged**
