### PR TITLE
Recommend from liked

### PR DESCRIPTION
**Pull request by jbochi**
Hi Benfred,

Thanks so much for this library!

I'm not sure if you are aware, but it's a standard practice to [sample users to get item factors](https://www.quora.com/How-do-I-speed-up-matrix-factorization-by-sampling-users-without-losing-precision) and then use those vectors to generate recommendations for all users.

The trick is to cache item factors only and compute user vectors on the fly to generate recommendations. Another advantage of this approach is that we can recompute user recommendations as soon as we have more data, without needing to rebuild the whole model.

This is a rough implementation of the idea. It introduces the `recommend_from_liked` method that accepts a list of items that were consumed by the user.

I did not reuse the code that computes the user vector in the iterations loop. With some refactoring, I think we could reuse the "solver", adding native and cg support. I can do that myself if you think this feature is helpful.

Any thoughts?

### CODE REVIEW

**Comment by jbochi** [comment]
Sure, I will do that!

**Comment by jbochi** [comment]
@benfred I believe the implementation is much cleaner now. I've also managed to reuse the non native code to compute user factors.

Please let me know what do you think about it now.

**Comment by benfred** [comment]
looks good to me! thanks for this

**Comment by farhadGithub** [comment]
Is it possible to share a reference/paper on how/why the `recalucate_user` method works?

**Pull request merged**
