### PR TITLE
Add an option to whether to include previously liked items or not

### PR DESCRIPTION
**Pull request by ita9naiwa**
Issue #131  says recommending already seen items will be good in some situations.

### CODE REVIEW

**Comment by ita9naiwa** [comment]
@srcolinas As far as I know, user-item matrix is required to build recommemdation to user.

**Comment by KiwiCampusChallenge** [comment]
Wouldn't it work if we just use the item_factors and user_factors properties?

**Comment by KiwiCampusChallenge** [comment]
Wouldn't it be enough to use item_factor user_factors ?

**Comment by srcolinas** [comment]
@ita9naiwa  wouldn't it be possible to build the recommendations based on `item_factors` and `user_factors`?

**Comment by ita9naiwa** [comment]
sorry,  its the case of nearest neighbour methods

**Comment by benfred** [comment]
@ita9naiwa thanks for the PR!

**Pull request merged**
