### PR TITLE
add recalculate_item to similar_items function

### PR DESCRIPTION
**Pull request by SeonbeomKim**
It can be used for new untrained items with user react logs.

### CODE REVIEW

**Comment by ita9naiwa** [comment]
It seems there's a problem with Travis

https://travis-ci.org/github/benfred/implicit/builds/712551147

why doesn't it show fail status...?

**Comment by SeonbeomKim** [comment]
> It seems there's a problem with Travis
> 
> https://travis-ci.org/github/benfred/implicit/builds/712551147
> 
> why doesn't it show fail status...?

**Comment by SeonbeomKim** [comment]
> It seems there's a problem with Travis
> 
> https://travis-ci.org/github/benfred/implicit/builds/712551147
> 
> why doesn't it show fail status...?

Thank you!!!

**Comment by ita9naiwa** [comment]
Great, Thanks!

**Pull request merged**
